@startuml
left to right direction

actor User as U
package Panier {
    usecase "Scanner un article" as P1
    usecase "Ajouter un produit à la main" as P2
    usecase "Valider son panier" as P3
    usecase "Enlever un article du panier" as P4
    usecase "Voir ses précédents paniers" as P5
}

usecase "Voir son profil" as Profil

package Participation {
    usecase "Voir son qota de participation" as Q1
    usecase "Ajouter une participation à un créneau" as Q2
    usecase "Retirer une participation à venir" as Q3
    usecase "Voir ses participations passées" as Q4
}

U --> P1
U --> P2
U --> P3
U --> P4
U --> P5
U --> Profil
U --> Q1
U --> Q2
U --> Q3
U --> Q4


@enduml
